apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-prod
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: vaultName
      value: "todo-secrets"
