apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-prod
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=neon-postgres.postgres.svc.cluster.local port=5432 user=postgres password=dapr-secret dbname=todo-app sslmode=disable"
  - name: versionColumnType
    value: "dapr_version"
  - name: tablePrefix
    value: "dapr"
  - name: actorStateStore
    value: "true"