apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-prod
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: database-connection
      key: connectionString
  - name: versionColumnType
    value: "dapr_version"
  - name: tablePrefix
    value: "dapr"
  - name: actorStateStore
    value: "true"
auth:
  secretStore: kubernetes-secrets